name: Build Pull Request

on: [push]


jobs:
  build-Entropy-Backend:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Compile project
      run: cd C2/Backend && pwd && mvn clean install > /dev/null && mvn package

    - name: Rename resulting jar
      run: cd C2/Backend && pwd && mv target/Entropy-1.0-SNAPSHOT-jar-with-dependencies.jar ./Entropy-Server-Backend.jar
      
    - name: Did it build?
      run: ls C2/Backend | grep "Entropy-Server-Backend.jar"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Entropy-Server-Backend
        path: C2/Backend/Entropy-Server-Backend.jar

  build-Entropy-Frontend:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: ubuntu-lastest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Clone repo
      uses: actions/checkout@v3
    
    - name: Build src directory
      run: cd C2/Frontend && go build ./src
    
    - name: Rename src executable
      run: mv C2/Framework/src C2/Framework/Entropy-Server-Frontend
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Frontend executable
        path: C2/Frontend/Entropy-Server-Frontend


