name: Build Pull Request

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Compile project
      run: cd C2/Backend && pwd && mvn clean install > /dev/null && mvn package

    - name: Rename resulting jar
      run: cd C2/Backend && pwd && mv target/Entropy-1.0-SNAPSHOT-jar-with-dependencies.jar ./Entropy.jar
      
    - name: Did it build?
      run: ls C2/Backend

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: pull-request-build
    #     path: build/libs/
